# -*- coding: utf-8 -*-
"""Copia de Clase_7ok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rdCdOt6zA4X0_ip3KnH1PsZnKoOdlJu4

La idea es que ustedes vayan resolviendo los ejercicios sin la necesidad de instalarse nada en sus computadoras. 
Antes que nada, creen una copia de este archivo en su ***Google Drive*** para tener permisos de edición, luego pueden compartirlo con quien quieran, tengan cuidado con los permisos al momento de compartir!!!!!!!. Si quieren, nos pueden compartir su documento a los docentes para que hagamos las correcciones y ayudemos con las dudas.

### Agustin: **agustin.otero@estudiantes.unahur.edu.ar** ###


En los bloques de código como el que les aparece aca abajo, se puede programar en Python, al pararse dentro del bloque, aparecerá un ícono de "*play*" en la esquina superior izquierda, "*clickeando*" en este ícono, se ejecuta el código escrito y se muestra la salida debajo, probemos:

Para "crear" una funcion debemos utilizar la palabra reservada **def** continuado de el nombre (en camelCase) y terminado por dos puntos **(:)**

Para **invocarla** bastara con "nombrarla" con los parentesis correspondientes, y se ejecutara el codigo que encierra.
"""

def saludador():
  #Proposito: Saluda al usuario
  print("hola")

saludador()

"""Las funciones no solo "hacen cosas" , sino que tambien pueden devolver valores para poder utilizarlos en otros lados."""

def pi():
  #Proposito: devolver el valor de pi con 5 decimales
  return(3.14159)

print(pi())

"""Tambien podemos añadirle **parametros** a nuestras funciones que actuaran como variables locales para nuestra funcion.
Estas variables nosotros tenemos que indicar de que tipo son para asi poder operar con ellas de forma "generica" y poder hacer n uestro codigo "generico" y reutilizable.
"""

def sumaYMuestra(num1, num2):
  #Proposito: sumar los valores num1 y num2 y mostrarlos en pantalla
  #Param: num1 = entero
  #       num2 = entero
  suma = num1 + num2
  print(int(suma))

sumaYMuestra(2,3)
sumaYMuestra(7,pi())

"""A las funciones que "devuelven" tambien se les pueden asignar parametros."""

def saludoPara_(nombre):
  #Proposito: saludar al usuario con el nombre indicado
  #Param: nombre = string
  return ("hola " + nombre)

print(saludoPara_("Jorge"))
print(saludoPara_("Ezequiel"))

"""A la funcion anterior le agregamos un **parametro por defecto.**

Esto significa que si el ususario al momento de invocar nuestra funcion no le indica el valor a tomar del parametro, el mismo tomara el valor por defecto que nosostros indicaremos al momento de crear el parametro.
"""

def saludoPara_(nombre = "Usuario"):
  #Proposito: saludar al usuario con el nombre indicado.
  #Param: nombre = string . Por defecto "usuario"
    return ("hola " + nombre)

print(saludoPara_("Jorge"))
print(saludoPara_())

"""Dentro de la documentacion tenemos que poner tambien la precondicion que debe cumplir el codigo previo a ejecutarlo, o las condiciones que van a hacer que nuestro codigo se rompa."""

def range(inicio = 0,final ,paso = 1)

def dividir(num1, num2):
  #Proposito: dividir num1 por num2 y mostrarlo por pantalla
  #Param: num1 = int
  #       num2 = int
  #Precon: num2 tiene que ser distinto de 0
  division = num1/num2
  print(division)

"""Ahora con lo aprendido vamos a resolver juntos este ejercicio:"""

def pedirNumero():
  #Proposito: pedir un entero por consola, y retornarlo.
  aux = int(input("ingrese un numero "))
  return(aux)

def sumador(x , y):
  #Proposito: Sumar los valores de x y x , y retornar la suma
  #Param: x = entero
  #       x = entero
  suma = x + y
  return (suma)

def restador(x , y):
  #Proposito: restar los valores de x y x , y retornar la resta
  #Param: x = entero
  #       x = entero
  resta = x - y
  return(resta)

def sumaOResta():
  #Proposito: pedirle al usuario que indique la operacion a realizar, e ingresar
  #   los datos para realizar la operacion. Terminado esto mostrar el resultado 
  #   o una indicacion de que hubo un error.
  variable = 0
  print("Ingrese 1 si quiere sumar")
  print("Ingrese 2 si quiere restar")
  numeroUsuario = pedirNumero()
  if numeroUsuario == 1:
    print("ingrese los datos a sumar")
    variable = sumador (pedirNumero() , pedirNumero())
    print(f"El resultado es {variable}")  
  elif numeroUsuario == 2:
    print("ingrese los datos a restar")
    variable = restador (pedirNumero() , pedirNumero())
    print(f"El resultado es {variable}")  
  else:
    print("Ingresó un valor equivocado")
  print("Termine")

  #USAR WHILE POR EVENTO

"""**Ejercicio 1**

Escribir una función que calcule el área de un círculo y otra que calcule el volumen de un cilindro usando la primera función.
"""

def areaDeUnCirculo (radio):
  area = 3,14 * radio ** 2
  print(area)

areaDeUnCirculo (4)

def volumenDeUnCirculo (radio):
  vol = 3,14 * area * radio **2
  print(vol)
volumenDeUnCirculo (5)

"""**Ejercicio 2**

Escribir una función que reciba una muestra de números en una lista y devuelva su promedio.

"""

def promedioDeNumeros (num1,num2,num3):
  prom = (num1 + num2 + num3) / 3
  print(prom)

promedioDeNumeros(5,7,9)

"""**Ejercicio 3**

Escribir la función factorial(), que reciba un número entero positivo y devuelva su factorial.

Factorial = El producto de todos los números enteros positivos desde 1 hasta el numero indicado.

Factorial(4) = 1*2*3*4 = 24
"""

def fact(n):
    if n == 0:
        r = 1
    else:
        r = n * fact(n - 1)
    return r
fact(5)

"""**Ejercicio 4**

Realiza una función llamada medio() que a partir de dos números, devuelva su punto medio. Cuando lo tengas comprueba el punto intermedio entre -12 y 24.


El punto medio de dos números corresponde a la suma de los dos números dividida entre 2

"""

def medio(num1,num2):
 med = (num1 + num2) / 2
 print(med)
medio(-12,24)

"""**Ejercicio 5**

Crear una función calcularMaxMin(list) que recibe una lista con valores numéricos y devuelve el valor máximo y el mínimo. Crea un programa que pida 10 números por teclado y muestre el máximo y el mínimo, utilizando la función anterior.
"""

def calcularMaxMin(numeros):
  menor = numeros [0]
  mayor = numeros [0]

  for n in numeros:
    if n < menor:
      menor = n
    if n > mayor:
      mayor = n
  return(menor,mayor)

lista = [0,1,3,5,7,9,11,13,15]
print(calcularMaxMin(lista))

num1 = int(input("Ingrese el primer numero"))
num2 = int(input("Ingrese el segundo numero"))
num3 = int(input("Ingrese el tercer numero"))
num4 = int(input("Ingrese el cuarto numero"))
num5 = int(input("Ingrese el quinto numero"))
num6 = int(input("Ingrese el sexto numero"))
num7 = int(input("Ingrese el septimo numero"))
num8 = int(input("Ingrese el octavo numero"))
num9 = int(input("Ingrese el noveno numero"))
num10 = int(input("Ingrese el decimo numero"))

lista2 = [num1,num2,num3,num4,num5,num6,num7,num8,num9,num10]
print(calcularMaxMin(lista2))

"""**Ejercicio 6**

Realiza una función llamada recortar(numero, minimo, maximo) que reciba tres parámetros. El primero es el número a recortar, el segundo es el límite inferior y el tercero el límite superior. La función tendrá que cumplir lo siguiente:


*   Devolver el límite inferior si el número es menor que éste
*   Devolver el límite superior si el número es mayor que éste.
*   Devolver el número sin cambios si no se supera ningún límite.

**Ejercicio 7**

Escribir una función que aplique un descuento que se le indica a un precio y otra que aplique el IVA a un precio.Si se invoca la función sin pasarle el porcentaje de IVA, deberá aplicar un 21%.

Escribir una tercera función que reciba un diccionario con los precios y porcentajes de  descuento de un carrito de compras, y una de las funciones anteriores, y utilice la función pasada para aplicar los descuentos o el IVA a los productos de la cesta y devolver el precio final de la cesta.
"""

def descuento (numero):
  #calcula el descuento del 20%
  des = (numero * 20) / 100
  des1 = numero - des
  print(des1)
descuento(100)

def iva(numero):
  #calcula y suma el iva al resultado
  ivaa = (numero * 21) / 100
  ivaaa = numero + ivaa
  print(ivaaa)
iva (100)
 

productos = {"tomate" : 80, "banana" : 70, "arroz" : 120, "manzanas": "130"}

print(descuento(productos))
print(iva(productos))

"""**Ejercicio 8**

Crear una función que calcule la temperatura media de un día a partir de la temperatura máxima y mínima. Crear un programa principal, que utilizando la función anterior, vaya pidiendo la temperatura máxima y mínima de cada día y vaya mostrando la media. El programa principal pedirá el número de días que se van a introducir.
"""

def temperaturaMedia (num1,num2):
  media = (num1 + num2) / 2
  print(media)
temperaturaMedia (15,30)

dias = int(input("Ingrese la cantidad de dias que desee"))
acum = 0
for i in range (dias):
  temp1 = int(input("Ingrese la temperatura minima del dia"))
  temp2 = int(input("ingrese la temperatura maxima del dia"))
  acumul = acum + 1
temperaturaMedia(temp1,temp2)

"""**Ejercicio 9**

Escribir dos funciones que permitan calcular:

*   La cantidad de segundos en un tiempo dado en horas, minutos y segundos.
*   La cantidad de horas, minutos y segundos de un tiempo dado en segundos.    

Escribe un programa principal con un menú donde se pueda elegir la opción de convertir a segundos, convertir a horas,minutos y segundos o salir del programa.

**Ejercicio 10**

Crear una funcion llamada “Login”, que recibe un nombre de usuario y una contraseña y te devuelve Verdadero si el nombre de usuario es “usuario1” y la contraseña es “asdasd”. Además recibe la variable que contiene el número de intentos que se ha intentado hacer login y si no se ha podido hacer login incremente este valor.

Crear un programa principal donde se pida un nombre de usuario y una contraseña y se intente hacer login, solamente tenemos tres oportunidades para intentarlo.
"""